### ISSUE TITLE
FVA result output

### ISSUE THREAD

**Issue by bgoli** [matthiaskoenig/fbc_curation#20]
Hi Matthias

Great work getting this together, a few issues I've noticed with regard to your FVA results.

1. In the example e_coli_core FVA result files, the reaction identifiers don't match the SBML reaction id's.
2. Reactions with negative fluxes have positive FVAmin and FVAmax values ... ?
3. What does a single *status* value mean for FVA (I use two status fields one for FVAmin and FVAmax respectively)?

As a control we should also include the optimal solution value for each reaction in the output and we can crosscheck that the optimal value falls within the FVA span.

Here is a comparison of some of the CBMPy and COBRApy output (we should decide on the roundoff at some point).

model	objective	reaction	status	minimum	maximum
e_coli_core	obj	R_AKGDH	optimal	5.0643756614820905	5.064375661482068
e_coli_core	obj	R_AKGt2r	optimal	0.0	0.0
e_coli_core	obj	R_ALCD2x	optimal	0.0	0.0
e_coli_core	obj	R_ATPM	optimal	8.39	8.389999999999965
e_coli_core	obj	R_ATPS4r	optimal	45.514009774517504	45.51400977451735
e_coli_core	obj	R_BIOMASS_Ecoli_core_w_GAM	optimal	0.8739215069684303	0.8739215069684301
e_coli_core	obj	R_CO2t	optimal	-22.80983331020495	-22.80983331020496

model	objective	reaction	status	minimum	maximum
e_coli_core	obj	AKGDH	optimal	5.064376	5.064376
e_coli_core	obj	AKGt2r	optimal	0.0	0.0
e_coli_core	obj	ALCD2x	optimal	0.0	0.0
e_coli_core	obj	ATPM	optimal	8.39	8.39
e_coli_core	obj	ATPS4r	optimal	45.51401	45.51401
e_coli_core	obj	BIOMASS_Ecoli_core_w_GAM	optimal	0.873922	0.873922
e_coli_core	obj	CO2t	optimal	22.809833	22.809833

Regards, Brett.

**Comment by matthiaskoenig** [comment]
Fixed the issues:
- correct reaction identifiers
- fixed bug with FVA negativity
- flux is added to FVA (reference flux)
- model is now model filename instead of model_id

**Comment by matthiaskoenig** [comment]
Forgot: Also added the requested metadata as `metadata.json` 
See the following for the fields
https://fbc-curation.readthedocs.io/en/latest/reference_files.html#metadata-file
