### ISSUE TITLE
Better filename for OMEX archive

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/fbc_curation#74]
Use combination of model filename, hash and timestamp.

**Comment by draeger** [comment]
What to do if an archive contains more than just a model file? For instance, also SBGN with a part of the model visualized – such a file could then have a diverging name, e.g., `central_carbon_metabolism.xml` or similar. Would you give priority to SBML file or SED-ML?

**Comment by matthiaskoenig** [comment]
@draeger Could point. I am not completely sure how to handle things at the moment. Issues exist in general for archives with multiple models. I.e. for what models should the FROG report be generated (probably for all). But what naming convention should be used for the different output files. I have to think a bit more about this, but useres complained that the hash alone as filename is not very useful.

**Comment by matthiaskoenig** [comment]
No perfect solution for this. Adding a `FROG_` prefix to the hash so that it is more clear that the omex is a FROG report.
