### ISSUE TITLE
Fix naming issues (harmonization)

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/fbc_curation#94]
* necessary to fix the model name

![image](https://user-images.githubusercontent.com/900538/202664349-c51131ae-e2c5-4e74-a2d3-5332d8099758.png)

**Comment by draeger** [comment]
Some thoughts:
* There might be numerous model files within one archive. Consequently, renaming them all to, e.g., `model.xml` will cause clashes.
* The objective function doesn not necessarily need a specific name or identifier but should be annotated with the right SBO term.
